""" Turn on syntax highlighting
syntax on


""" Line number (hybrid mode from Vim version 7.4)
set relativenumber
set number


""" Insert mode
" highlight the cursor line, default is underline
:autocmd InsertEnter,InsertLeave * set cul!  " oneliner as the 2 line below
":autocmd InsertEnter * set cul
":autocmd InsertLeave * set nocul
" change the default highlight from underline to background color
hi CursorLine cterm=NONE ctermbg=black
" change the cursor shape in insert mode (for gnome-terminal version >= 3.16)
if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[1 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' | 
    \   silent execute '!echo -ne "\e[5 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[3 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif


""" Fix Unix-based system backspace problem
set backspace=2 " make backspace work like most other apps, alternative to the line below
"set backspace=indent,eol,start


""" Define some nice abbreviations:
ab #d #define
ab #i #include


""" Converting tabs to spaces
set tabstop=4 shiftwidth=4 expandtab  " oneliner as the 3 lines below
"set expandtab     " insert space characters whenever the tab key is pressed
"set tabstop=4     " set number of space when typing tab
"set shiftwidth=4  " change the number of space characters inserted for indentation
"retab             " change all the existing tab characters to match the current tab settings


""" Start vim in utf-8 encoding mode
set encoding=utf-8  " The encoding displayed.
set fileencoding=utf-8  " The encoding written to file.


""" Searching
set hlsearch " highlight all search matches
" press return to temporarily get out of the highlighted search
nnoremap <CR> :nohlsearch<CR>


""" Setting statusline
" colors
hi User0 ctermfg=Black       ctermbg=Green
hi User1 ctermfg=LightGray   ctermbg=Black
hi User2 ctermfg=LightGray   ctermbg=Brown
hi User3 ctermfg=LightGray   ctermbg=DarkRed
hi User4 ctermfg=LightGray   ctermbg=DarkGreen
hi User5 ctermfg=LightGray   ctermbg=Blue
hi User6 ctermfg=LightGray   ctermbg=DarkCyan
hi User7 ctermfg=LightGray   ctermbg=DarkBlue
hi User8 ctermfg=LightGray   ctermbg=DarkGrey
" statusline
set laststatus=2
set statusline=
set statusline+=%0*\[%n]                                  "buffernr
set statusline+=%1*\ %<%F\ %m\                            "File+path + modified flag
set statusline+=%2*\ %y\                                  "FileType
set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..) 
set statusline+=%5*\ %{&spelllang}\ %{HighlightSearch()}\  "Spellanguage & Highlight on?
set statusline+=%6*\ %=\ row:%l/%L\ (%03p%%)\             "Rownumber/total (%)
set statusline+=%7*\ col:%03c\                            "Colnr
set statusline+=%8*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.
" functions
function! HighlightSearch()
  if &hls
    return 'H'
  else
    return ''
  endif
endfunction
